version: '3.8'

services:
  db:
    build: .
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "K4ntarbooks"
    ports:
      - "1433:1433"
    volumes:
      - data:/var/opt/mssql

volumes:
  data:
